apiVersion: batch/v1
kind: CronJob
metadata:
  name: kiss-elastic-sync-job-sharepoint
spec:
  schedule: "*/59 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kiss-elastic-sync
            image: ghcr.io/klantinteractie-servicesysteem/kiss-elastic-sync
            imagePullPolicy: Always
            args:
            - sharepoint
            env:
            - name: SHAREPOINT_PAGE_URL
              value: "https://icattnl.sharepoint.com/sites/synctooltestsite/SitePages/SyncTool-test-pagina.aspx"
            envFrom:
            - secretRef:
                name: kiss-secrets
            - configMapRef:
                name: kiss-config
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              readOnlyRootFilesystem: true
              runAsUser: 10000
              capabilities:
                drop: [ALL]
          restartPolicy: Never
